from depth_estimation.naive_bbox_depth.constants import (
    BUFFER_SIZE,
    DEVICE,
    FOURCC,
    FPS_HINT,
    HEIGHT,
    KEY_QUIT as NAIVE_KEY_QUIT,
    KEY_TOGGLE_GATING as NAIVE_KEY_TOGGLE_GATING,
    WIDTH,
)

# Methods to run in the top-level live depth reviewer.
# Keep this list small for real-time performance.
# Example future config: ("naive", "unidepth")
DEPTH_LIVE_REVIEW_METHODS = ("naive",)

# Camera settings.
DEPTH_LIVE_REVIEW_DEVICE = DEVICE
DEPTH_LIVE_REVIEW_WIDTH = WIDTH
DEPTH_LIVE_REVIEW_HEIGHT = HEIGHT
DEPTH_LIVE_REVIEW_FPS_HINT = FPS_HINT
DEPTH_LIVE_REVIEW_FOURCC = FOURCC
DEPTH_LIVE_REVIEW_BUFFER_SIZE = BUFFER_SIZE

# Window + overlay.
DEPTH_LIVE_REVIEW_WINDOW_NAME = "Live Depth Review"
DEPTH_LIVE_REVIEW_USE_SIDE_PANEL = True
DEPTH_LIVE_REVIEW_SIDE_PANEL_WIDTH = 560
DEPTH_LIVE_REVIEW_SIDE_PANEL_BG_COLOR = (22, 22, 22)
DEPTH_LIVE_REVIEW_SIDE_PANEL_TEXT_COLOR = (230, 230, 230)
DEPTH_LIVE_REVIEW_SIDE_PANEL_ACCENT_COLOR = (120, 220, 120)
DEPTH_LIVE_REVIEW_LINE_HEIGHT = 22
DEPTH_LIVE_REVIEW_TEXT_THICKNESS = 2

# Controls.
KEY_QUIT = set(NAIVE_KEY_QUIT)
KEY_TOGGLE_GATING = set(NAIVE_KEY_TOGGLE_GATING)
