# square.py
SQUARE_HEIGHT_M = 0.50
SQUARE_FORWARD_SPEED = 0.25
SQUARE_YAW_RATE = 60.0
SQUARE_SIDE_LENGTH = 0.60
SQUARE_PAUSE_S = 0.30

# height_sequence.py
HEIGHT_SEQUENCE_HEIGHTS = (0.5,)
HEIGHT_SEQUENCE_HOLD_S = 1.0
HEIGHT_SEQUENCE_MODE = "absolute"
HEIGHT_SEQUENCE_TAKEOFF_HEIGHT = 0.5

# origin_to_point.py
ORIGIN_TO_POINT_TARGET_X = 0.6
ORIGIN_TO_POINT_TARGET_Y = 0.0
ORIGIN_TO_POINT_HEIGHT_M = 0.5
ORIGIN_TO_POINT_KP = 0.8
ORIGIN_TO_POINT_MAX_VEL = 0.25
ORIGIN_TO_POINT_TOL = 0.05
ORIGIN_TO_POINT_DT = 0.05

# roll_pitch_yaw.py
ROLL_PITCH_YAW_TEST = "roll"  # "roll", "pitch", "yaw", "all"
ROLL_PITCH_YAW_REPEATS = 5
ROLL_PITCH_YAW_HEIGHT_M = 0.5
ROLL_PITCH_YAW_VXY = 0.2
ROLL_PITCH_YAW_YAWRATE = 60.0
ROLL_PITCH_YAW_ANGLE_DEG = 90.0
ROLL_PITCH_YAW_LEG_S = 0.6
ROLL_PITCH_YAW_PAUSE_S = 0.4
