MISSION = "square"

# Teleoperation defaults used by DroneControlApp.
TELEOP_DEFAULT_TARGET_Z = 0.5
TELEOP_INVERT_ROLL = True
TELEOP_INVERT_YAW = True

# Runner behavior defaults.
TAKEOVER_ON_ANY_INPUT = True
LAND_AFTER_MISSION_IF_NO_TAKEOVER = True

# App-level mission presets.
SQUARE_MISSION_HEIGHT_M = 0.5
SQUARE_MISSION_FORWARD_SPEED = 1.0
SQUARE_MISSION_YAW_RATE = 60.0
SQUARE_MISSION_SIDE_LENGTH = 1.5

HEIGHT_SEQUENCE_HEIGHTS = (0.7, 0.2, 0.4)
HEIGHT_SEQUENCE_HOLD_S = 1.0
HEIGHT_SEQUENCE_MODE = "absolute"
HEIGHT_SEQUENCE_TAKEOFF_HEIGHT = 0.5

ORIGIN_TO_POINT_TARGET_X = 0.6
ORIGIN_TO_POINT_TARGET_Y = 0.0
ORIGIN_TO_POINT_HEIGHT_M = 0.5

ROLL_PITCH_YAW_TEST = "all"
ROLL_PITCH_YAW_REPEATS = 3
ROLL_PITCH_YAW_HEIGHT_M = 0.5
ROLL_PITCH_YAW_VXY = 1.0
ROLL_PITCH_YAW_YAWRATE = 60.0
ROLL_PITCH_YAW_ANGLE_DEG = 180.0
ROLL_PITCH_YAW_LEG_S = 2.0
ROLL_PITCH_YAW_PAUSE_S = 1.0
